from datetime import datetime
from typing import Dict, Any

class ReportService:
    @staticmethod
    def generate_daily_report(user_id: str, market_data: Dict[str, Any], journal_entries: list) -> str:
        """
        Generates a markdown formatted daily trading report.
        """
        report_date = datetime.now().strftime("%Y-%m-%d")
        
        md_content = f"# Daily Trading Report - {report_date}\n\n"
        
        # 1. Market Overview
        md_content += "## 1. Market Overview\n"
        if market_data:
            for pair, data in market_data.items():
                md_content += f"- **{pair}**: Bid: {data.get('bid')}, Ask: {data.get('ask')}\n"
        else:
            md_content += "No market data available for today.\n"
        
        md_content += "\n"
        
        # 2. Trading Journal Summary
        md_content += "## 2. Trading Journal Summary\n"
        if journal_entries:
            total_pl = 0.0
            for entry in journal_entries:
                pl = entry.get('profit_loss', 0.0)
                total_pl += pl if pl else 0.0
            
            md_content += f"**Total Trades Today**: {len(journal_entries)}\n"
            md_content += f"**Total Profit/Loss**: {total_pl:.2f}\n\n"
            
            md_content += "### Trade Details\n"
            for entry in journal_entries:
                md_content += f"- {entry.get('direction')} {entry.get('currency_pair')} | "
                md_content += f"Entry: {entry.get('entry_price')} | Exit: {entry.get('exit_price')} | "
                md_content += f"P/L: {entry.get('profit_loss')}\n"
        else:
            md_content += "No trades recorded for today.\n"
            
        md_content += "\n"
        md_content += "---\n"
        md_content += "Report generated by AI Forex Trading Assistant."
        
        return md_content
